# Знакомство с `torch.Tensor`

__Автор задач: Блохин Н.В. (NVBlokhin@fa.ru)__

Материалы:
* Deep Learning with PyTorch (2020) Авторы: Eli Stevens, Luca Antiga, Thomas Viehmann
* https://pytorch.org/docs/stable/torch.html


## Задачи для совместного разбора

In [4]:
import torch as th

1\. Создайте тензор и исследуйте его основные характеристики

In [4]:
a = th.randint(0,10, size = (10,5), dtype = th.float32)

In [5]:
a.dtype

torch.float32

In [7]:
a.pow(2)

tensor([[ 1., 16., 64.,  9.,  0.],
        [25.,  1., 81., 64.,  9.],
        [36., 25., 49.,  9.,  9.],
        [64., 64., 36.,  1.,  1.],
        [ 9., 81.,  1.,  0., 36.],
        [49.,  1., 16.,  4.,  0.],
        [ 4.,  1., 64., 64.,  1.],
        [16., 36.,  0., 36.,  4.],
        [64., 49.,  4., 25.,  4.],
        [ 4., 49., 25.,  9., 16.]])

In [10]:
import numpy as np
np.mean(a)

TypeError: ignored

2\. Создайте трехмерный тензор и рассмотрите основные способы индексирования по нему

In [21]:
t = th.randint(0,100, size = (5,3,3))
t

tensor([[[40, 56, 88],
         [63, 96, 72],
         [24, 99, 53]],

        [[78, 26, 67],
         [97, 84, 56],
         [63, 52, 22]],

        [[46, 22, 61],
         [44, 82, 25],
         [39, 76,  2]],

        [[68, 91, 75],
         [49, 94, 15],
         [39, 58, 88]],

        [[65, 86, 96],
         [85, 77, 86],
         [ 1, 74, 59]]])

In [22]:
t[0] #t[0,:,:]

tensor([[40, 56, 88],
        [63, 96, 72],
        [24, 99, 53]])

In [26]:
t[:, 0]

tensor([[40, 56, 88],
        [78, 26, 67],
        [46, 22, 61],
        [68, 91, 75],
        [65, 86, 96]])

In [28]:
t[:, :, [0,2,0,2,0]]

tensor([[[40, 88, 40, 88, 40],
         [63, 72, 63, 72, 63],
         [24, 53, 24, 53, 24]],

        [[78, 67, 78, 67, 78],
         [97, 56, 97, 56, 97],
         [63, 22, 63, 22, 63]],

        [[46, 61, 46, 61, 46],
         [44, 25, 44, 25, 44],
         [39,  2, 39,  2, 39]],

        [[68, 75, 68, 75, 68],
         [49, 15, 49, 15, 49],
         [39, 88, 39, 88, 39]],

        [[65, 96, 65, 96, 65],
         [85, 86, 85, 86, 85],
         [ 1, 59,  1, 59,  1]]])

3\. Создайте тензор (4х4) и модифицируйте следующим образом: ко всем четным столбцам прибавьте 1, из нечетных вычтите 1.

4\. Исследуйте совместимость `torch` с `numpy` и `sklearn`

## Задачи для самостоятельного решения

<p class="task" id="1"></p>

1\. Создайте двумерный тензор размера (100000, 10), заполненный нулями. Используя прихотливое индексирование, поставьте в каждой строке тензора ровно одну единицу в случайно выбранном столбце. Рассчитайте и выведите на экран вероятности $p_i$ того, что для случайно выбранной строки в столбце $i$ будет стоять единица.

In [1]:
import torch as th

In [2]:
t = th.zeros(size=(100000, 10))

In [3]:
indexes = th.randint(0, 10, size=(100000,))

In [4]:
indexes

tensor([0, 7, 5,  ..., 8, 5, 4])

In [5]:
t

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [6]:
t[th.arange(t.shape[0]), indexes] = 1

In [7]:
t.mean(axis=0)

tensor([0.1020, 0.1003, 0.1000, 0.1009, 0.0997, 0.0977, 0.1003, 0.0993, 0.1001,
        0.0997])

<p class="task" id="2"></p>

2\. При помощи прихотливого индексирования для двумерного тензора размерности (10, 10), состоящего из случайных целых чисел в пределах от 0 до 10, получите тензор элементов, находящихся сразу над побочной диагональю.

In [8]:
t = th.randint(0, 11, size=(10, 10))

In [9]:
t

tensor([[ 9,  6,  6,  9,  4,  5,  6,  2,  3,  6],
        [ 1,  1,  4,  5,  1, 10,  8, 10,  0,  7],
        [ 4,  2,  1,  4,  2,  8,  2, 10,  9,  4],
        [ 6,  1,  2, 10,  9,  8,  0,  8,  8,  1],
        [10,  8,  3,  4,  1,  1,  9,  0,  1,  2],
        [ 6,  6,  1,  0,  2,  1,  0,  2,  6,  0],
        [ 7,  5,  1,  1,  7,  8, 10,  7,  2,  3],
        [ 6,  5,  6,  9,  1,  8,  3,  1,  6,  9],
        [ 1,  5,  9,  9,  5,  8,  7,  5,  4,  8],
        [ 7,  3,  0,  5,  6,  0,  4,  4,  3,  6]])

In [10]:
rows = th.arange(0,t.shape[0]-1)

In [11]:
columns = th.arange(t.shape[0] -2 , -1, -1)

In [12]:
t[rows,columns]

tensor([ 3, 10,  2,  8,  1,  0,  1,  5,  1])

<p class="task" id="3"></p>

3\. Создайте двумерный тензор $t$ размерности (5, 5), состоящий из случайных чисел в пределах от 0 до 100. Обнулить все значения в массиве, расположенные вне квадрата размера 3х3 вокруг максимального элемента. Если максимумов несколько, обнулите элементы около любого из них.

In [13]:
t = th.randint(0, 101, (5, 5))

In [14]:
t

tensor([[12, 12, 18, 83, 36],
        [41, 16,  0, 67, 53],
        [25, 66, 52, 95, 52],
        [47, 77, 83, 40, 90],
        [16, 31, 54, 46, 52]])

In [15]:
res = t.clone()

In [16]:
max_value = t.max()
max_indices = th.where(t == max_value)

In [17]:
min_row = max(0, max_indices[0][0].item() - 1)
max_row = min(4, max_indices[0][0].item() + 1)
min_col = max(0, max_indices[1][0].item() - 1)
max_col = min(4, max_indices[1][0].item() + 1)

In [18]:
mask = th.ones((5, 5), dtype=th.bool)
mask[min_row:max_row+1, min_col:max_col+1] = False
res[mask] = 0

In [19]:
res

tensor([[ 0,  0,  0,  0,  0],
        [ 0,  0,  0, 67, 53],
        [ 0,  0, 52, 95, 52],
        [ 0,  0, 83, 40, 90],
        [ 0,  0,  0,  0,  0]])

<p class="task" id="4"></p>

4\. Создайте трехмерный массив размерности (2, 5, 5) на основе решения задачи 3 (объедините исходный и результирущий тензор вдоль нулевой оси). Сохраните полученный трехмерный тензор в файл `tensor.pt`. Загрузите полученный тензор и покажите, что все элементы двух тензоров совпадают.

In [20]:
t3 = th.stack([t, res], dim=0)

In [21]:
t3

tensor([[[12, 12, 18, 83, 36],
         [41, 16,  0, 67, 53],
         [25, 66, 52, 95, 52],
         [47, 77, 83, 40, 90],
         [16, 31, 54, 46, 52]],

        [[ 0,  0,  0,  0,  0],
         [ 0,  0,  0, 67, 53],
         [ 0,  0, 52, 95, 52],
         [ 0,  0, 83, 40, 90],
         [ 0,  0,  0,  0,  0]]])

In [22]:
th.save(t3, 'tensor.pt')

In [23]:
t_load = th.load('tensor.pt')

In [24]:
t_load == t3

tensor([[[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]],

        [[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]]])

<p class="task" id="5"></p>

5\. Создайте четырехмерный массив `t` размерности (2, 3, 5, 5), заполненный случайными целыми числами от 1 до 10 (сами значения должны быть представлены типом float32). Рассчитайте среднее значение для каждого двумерного тензора `t[i, j, :, :]`. Представьте результат в виде трехмерного тензора размера (2, 3, 1).

In [25]:
t = th.randint(1, 11, size=(2, 3, 5, 5), dtype=th.float32)

In [26]:
mean_values = th.mean(t, dim=(2, 3), keepdim=True)



mean_values


tensor([[[[4.8400]],

         [[5.7600]],

         [[5.0400]]],


        [[[5.2000]],

         [[6.0800]],

         [[5.1600]]]])

<p class="task" id="6"></p>

6\. Создайте одномерный тензор размера `N=100_000_000`, заполненный числами из экспоненциального распредления с параметром $\lambda=5$. Рассчитайте значения для построения гистограммы при помощи пакета `torch`. Визуализируйте гистограмму. Проверьте возможность использования GPU. При наличии GPU перенесите созданный тензор в память GPU, повторите вычисления. Сравните время расчетом с и без использования GPU.

<p class="task" id="7"></p>

7\. Создайте четырехмерный тензор размера (10, 6, 6, 3), заполненный случайными целыми числами от 0 до 255. Считая, что данный тензор представляет собой батч из 10 картинок размера 6х6 в формате RGB, измените тензор следующим образом. Для оттенков красного обнулите все столбцы, кроме первых двух; для оттенков зеленого обнулите столбцы со второго по четвертый; для оттенков синего обнулите пятый и шестой столбцы. Для выполнения задания используйте механизм распространения.

## Обратная связь
- [ ] Хочу получить обратную связь по решению