#  Forward pass

__Автор задач: Блохин Н.В. (NVBlokhin@fa.ru)__

Материалы:
* Deep Learning with PyTorch (2020) Авторы: Eli Stevens, Luca Antiga, Thomas Viehmann
* https://pytorch.org/docs/stable/generated/torch.matmul.html
* https://machinelearningmastery.com/choose-an-activation-function-for-deep-learning/
* https://machinelearningmastery.com/loss-and-loss-functions-for-training-deep-learning-neural-networks/

## Задачи для совместного разбора

1\. Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте нейрон с заданными весами `weights` и `bias`. Пропустите вектор `inputs` через нейрон и выведите результат.

In [ ]:
# pip install torch

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import torch

In [ ]:
class Neuron:
    def __init__(self, weights, bias):
    # <создать атрибуты объекта weights и bias>
      self.weights = weights
      self.bias = bias

    def forward(self, inputs):
      return inputs@self.weights+self.bias



In [ ]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([-0.2, 0.3, -0.5, 0.7])
bias = 3.14

In [ ]:
n = Neuron(weights, bias)
y = n.forward(inputs)


In [ ]:
y

tensor(4.8400)

2\. Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию активации ReLU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/f4353f4e3e484130504049599d2e7b040793e1eb)

Создайте матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверьте работоспособность функции активации.

In [ ]:
class ReLU:
    def forward(self, inputs):
    # <реализовать логику ReLU>
        pass

In [ ]:
class ReLU:
    def forward(self, inputs):
        return torch.clip(inputs,min=0)

In [ ]:
X = torch.randn(4, 3)
X

tensor([[-1.4098,  0.6699, -0.4273],
        [ 0.5346,  0.8835, -0.7761],
        [ 0.1086,  0.8665,  0.0096],
        [-0.9992,  0.1900,  1.9118]])

In [ ]:
relu = ReLU()


output = relu.forward(X)

output

tensor([[0.0000, 0.6699, 0.0000],
        [0.5346, 0.8835, 0.0000],
        [0.1086, 0.8665, 0.0096],
        [0.0000, 0.1900, 1.9118]])

3\. Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию потерь MSE:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/e258221518869aa1c6561bb75b99476c4734108e)
где $Y_i$ - правильный ответ для примера $i$, $\hat{Y_i}$ - предсказание модели для примера $i$, $n$ - количество примеров в батче.

In [ ]:
class MSELoss:
      def forward(self, y_pred, y_true):
        return (y_pred-y_true).pow(2).mean()

In [ ]:
y_pred = torch.tensor([1.0, 3.0, 5.0])
y_true = torch.tensor([2.0, 3.0, 4.0])

In [ ]:
criterion = MSELoss()
criterion.forward( y_pred, y_true)

tensor(0.6667)

## Задачи для самостоятельного решения

### Cоздание полносвязных слоев

<p class="task" id="1_1"></p>

1\.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте полносвязный слой из `n_neurons` нейронов с `n_features` весами у каждого нейрона (инициализируются из стандартного нормального распределения) и опциональным вектором смещения.

$$y = xW^T + b$$

Пропустите вектор `inputs` через слой и выведите результат. Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.

- [x] Проверено на семинаре

In [ ]:
class Linear:
    def __init__(self, n_neurons, n_features, bias: bool = False):
        pass

    def forward(self, inputs):
        pass

In [ ]:
# inputs: batch_size(3) x 4
inputs = torch.tensor([[1, 2, 3, 2.5],
                       [2, 5, -1, 2],
                       [-1.5, 2.7, 3.3, -0.8]])

In [ ]:
class Linear:
    def __init__(self, n_neurons, n_features, bias: bool = False):
        self.w = torch.randn(n_neurons, n_features)
        if bias:
           self.b = torch.randn(n_neurons)
        else:
           self.b = None

    def forward(self, inputs):
        output = inputs @ self.w.t()
        if self.b is not None:
            output += self.b
        return output


In [ ]:
linear_layer = Linear(n_neurons=10, n_features=4)
output = linear_layer.forward(inputs)

In [ ]:
output

tensor([[ 1.7537,  0.6667,  2.4158,  5.3994,  3.5203, -0.5887, -1.6789, -0.5052,
          5.2771, -0.1554],
        [10.9236,  3.3885,  0.5877,  5.1805,  5.4771,  1.5011, -2.9877, -1.8675,
         -3.0159, -3.3321],
        [-2.2393, -1.4303,  1.4585, -0.3376, -0.1846,  1.0567, -3.9485,  2.9507,
          0.1137, -1.5886]])

1

<p class="task" id="1_2"></p>

1\.2 Используя решение предыдущей задачи, создайте 2 полносвязных слоя и пропустите тензор `inputs` последовательно через эти два слоя. Количество нейронов в первом слое выберите произвольно, количество нейронов во втором слое выберите так, чтобы результатом прогона являлась матрица `batch_size x 7`.

- [x] Проверено на семинаре

In [ ]:
layer1 = Linear(n_neurons=10, n_features=4)
layer2 = Linear(n_neurons=7, n_features=10)

In [ ]:
output1 = layer1.forward(inputs)

In [ ]:
output1

tensor([[-7.1877,  4.7722,  7.6566, -4.1295,  7.9858,  1.8210,  0.1960, -1.3199,
          6.3539, -0.9664],
        [-3.5322,  1.6815,  6.3844,  1.5424,  5.9606, -4.3085,  3.5767, -5.1580,
          5.3447,  0.0147],
        [-2.2465,  5.1041, -0.8427, -4.8925,  2.8111,  4.5355,  4.1751,  3.2480,
         -0.0716,  0.2955]])

In [ ]:
output2 = layer2.forward(output1)

In [ ]:
output2

tensor([[ -1.8252,  -9.5581,   7.7926,   9.3101,  -4.6363,   1.0317,  10.1012],
        [ -3.8969,  12.3756,   5.6654,  -2.2211,   5.7136,  15.7015,   6.2562],
        [ -1.3369, -25.9585,   5.8134,  12.1736,  -5.1391, -11.4335,   0.7932]])

### Создание функций активации

<p class="task" id="2_1"></p>

2\.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию активации softmax:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/6d7500d980c313da83e4117da701bf7c8f1982f5)

$$\overrightarrow{x} = (x_1, ..., x_J)$$

Создайте матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверьте работоспособность функции активации. Строки матрицы трактовать как выходы линейного слоя некоторого классификатора для 4 различных примеров. Функция должна применяться переданной на вход матрице построчно.

- [ ] Проверено на семинаре

In [ ]:
class Softmax:
    def forward(self, inputs):
        # <реализовать логику Softmax>
        pass

In [ ]:
class Softmax:
    def forward(self, inputs):
        return torch.exp(inputs) / torch.exp(inputs).sum(dim=1).view(-1, 1)


In [ ]:
inputs = torch.randn(size=(4, 3))

In [ ]:
inputs

tensor([[-0.7908,  2.0011, -1.3943],
        [ 0.6787,  0.2453, -0.7228],
        [ 0.5589, -0.3470,  0.6150],
        [ 0.2769, -0.8328, -0.9713]])

In [ ]:
s = Softmax()

In [ ]:
s.forward(inputs)

tensor([[0.0560, 0.9134, 0.0306],
        [0.5278, 0.3422, 0.1300],
        [0.4062, 0.1642, 0.4296],
        [0.6186, 0.2039, 0.1775]])

<p class="task" id="2_2"></p>

2.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию активации ELU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/eb23becd37c3602c4838e53f532163279192e4fd)

Создайте матрицу размера 4x3, заполненную числами из стандартного нормального распределения, и проверьте работоспособность функции активации.

- [ ] Проверено на семинаре

In [ ]:
class ELU:
    def __init__(self, alpha: float):
        pass

    def forward(self, inputs):
        # <реализовать логику ELU>
        pass

In [5]:
class ELU:
    def __init__(self, alpha: float):
        self.alpha = alpha

    def forward(self, inputs):
        positive_mask = inputs > 0
        negative_values = self.alpha * (torch.exp(inputs) - 1)
        output = torch.where(positive_mask, inputs, negative_values)

        return output


In [6]:
inputs = torch.randn(size=(4, 3))
inputs

tensor([[-0.5380, -0.7802,  0.0081],
        [ 0.3602,  0.9154, -1.5675],
        [ 1.4642, -0.2282, -1.9667],
        [ 0.1675,  0.9709,  0.2402]])

In [7]:
ELU(1.5).forward(inputs)

tensor([[-0.6241, -0.8125,  0.0081],
        [ 0.3602,  0.9154, -1.1871],
        [ 1.4642, -0.3060, -1.2901],
        [ 0.1675,  0.9709,  0.2402]])

### Создание функции потерь

<p class="task" id="3_1"></p>

3\.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию потерь CrossEntropyLoss:

$$y_i = (y_{i,1},...,y_{i,k})$$
<img src="https://i.ibb.co/93gy1dN/Screenshot-9.png" width="200">

$$ CrossEntropyLoss = \frac{1}{n}\sum_{i=1}^{n}{L_i}$$
где $y_i$ - вектор правильных ответов для примера $i$, $\hat{y_i}$ - вектор предсказаний модели для примера $i$; $k$ - количество классов, $n$ - количество примеров в батче.

Создайте полносвязный слой с 3 нейронами и прогнать через него батч `inputs`. Полученный результат пропустите через функцию активации Softmax. Посчитайте значение функции потерь, трактуя вектор `y` как вектор правильных ответов.

- [ ] Проверено на семинаре

In [ ]:
class CrossEntropyLoss:
      def forward(self, y_pred, y_true):
    # <реализовать логику функции потерь>
        pass

In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5],
                        [2, 5, -1, 2],
                        [-1.5, 2.7, 3.3, -0.8]])
y = torch.tensor([1, 0, 0])

<p class="task" id="3_2"></p>

3.2 Модифицируйте MSE, добавив L2-регуляризацию.

$$MSE_R = MSE + \lambda\sum_{i=1}^{m}w_i^2$$

где $\lambda$ - коэффициент регуляризации; $w_i$ - веса модели.

- [ ] Проверено на семинаре

In [ ]:
class MSERegularized:
    def __init__(self, lambda_):
        pass

    def data_loss(self, y_pred, y_true):
        # <подсчет первого слагаемого из формулы>
        pass

    def reg_loss(self, weights):
        # <подсчет второго слагаемого из формулы>
        pass

    def forward(self, y_pred, y_true, weights):
        return self.data_loss(y_pred, y_true) + self.reg_loss(weights)

In [ ]:
y_pred = torch.tensor([-0.5, 1, 1.7])
y_true = torch.tensor([0, 0.6, 2.3])
weights = torch.normal(0, 5, (10, 1))

In [ ]:
class MSERegularized:
    def __init__(self, lambda_):
        self.lambda_ = lambda_

    def data_loss(self, y_pred, y_true):
        return (y_pred-y_true).pow(2).mean()

    def reg_loss(self, weights):
        return self.lambda_ * (weights**2).sum()

    def forward(self, y_pred, y_true, weights):
        data_loss = self.data_loss(y_pred, y_true)
        reg_loss = self.reg_loss(weights)
        return data_loss + reg_loss

In [ ]:
MSER = MSERegularized(0.2)

MSER.forward(y_pred, y_true, weights)

tensor(71.2578)

## Обратная связь
- [ ] Хочу получить обратную связь по решению